# Config file for automatic testing at travis-ci.org
dist: trusty
language: python
python:
  - 3.5
  - 3.6

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: required

# XGBOOST required package
before_install:
    - sudo apt-get update
    - sudo apt-get -y install libaio1

# Command to install dependencies
install: pip install -U tox-travis codecov

after_success: codecov

# Command to run tests
script: tox

deploy:

  - provider: pages
    skip-cleanup: true
    github-token: "$GITHUB_TOKEN"
    keep-history: true
    local-dir: docs/_build/html
    target-branch: gh-pages
    on:
      branch: master
      python: 3.6
